site_name: LightDrive
site_url: https://nmstr.github.io/LightDrive/
theme:
  name: "material"
  logo: assets/lightdrive.svg
  favicon: assets/lightdrive.svg
  features:
    - navigation.tabs
    - navigation.expand
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Nmstr/LightDrive

nav:
  - Home: 'index.md'
  - Contribute: 'contributing.md'
