[project]
name = "LightDrive"
version = "0.0.0-dev"
description = "Create Your Own Light Shows"
readme = "README.md"
requires-python = ">=3.8"
authors = [
    { name="Namester (Nmstr)", email="publicNamester@gmail.com" }
]
keywords = ["music", "light", "show", "light show", "lighting", "PySide6", "QT", "GUI", "QML"]
classifiers = [
    "Intended Audience :: End Users/Desktop",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",

    "Topic :: Artistic Software",
    "Topic :: Home Automation",
]
dependencies = [
    "pyside6>=6.6.3.1",
]
[project.urls]
Source = "https://github.com/Nmstr/LightDrive"
Issues = "https://github.com/Nmstr/LightDrive/issues"

[tool.ruff]
lint.select = ["E4", "E7", "E9", "F", "N8"]
